from __future__ import annotations

import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest import mock

from src.db import connect_database, initialize_database
from src.db_protocol import PostgreSQLConnection
from src.postgres_migrations import (
    MIGRATION_LOCK_ID,
    MIGRATION_NAMES,
    _validate_migration_state,
    migrate_postgresql,
    translate_schema,
)


class PostgreSQLMigrationTests(unittest.TestCase):
    def test_migration_registry_matches_sqlite_history(self) -> None:
        with TemporaryDirectory() as temporary_directory:
            connection = connect_database(Path(temporary_directory) / "registry.sqlite3")
            try:
                initialize_database(connection)
                sqlite_names = [
                    str(row[0]) for row in connection.execute(
                        "SELECT name FROM schema_migrations ORDER BY version"
                    )
                ]
            finally:
                connection.close()
        self.assertEqual(sqlite_names, list(MIGRATION_NAMES))

    def test_canonical_schema_contains_upgraded_moderation_columns(self) -> None:
        from src.db import SCHEMA_SQL

        translated = translate_schema(SCHEMA_SQL)
        for column in (
            "assigned_operator_id",
            "escalated_at",
            "provider_confirmed_at",
            "provider_event_id",
        ):
            self.assertIn(column, translated)

    def test_translation_removes_sqlite_only_schema_constructs(self) -> None:
        translated = translate_schema(
            """CREATE TABLE sample (id INTEGER PRIMARY KEY, payload BLOB,
                   created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
               CREATE VIRTUAL TABLE IF NOT EXISTS observation_fts USING fts5(text);
               CREATE TRIGGER IF NOT EXISTS observations_fts_insert AFTER INSERT ON sample
               BEGIN SELECT 1; END;"""
        )
        self.assertIn("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", translated)
        self.assertIn("BYTEA", translated)
        self.assertIn("DEFAULT (CURRENT_TIMESTAMP::text)", translated)
        self.assertNotIn("VIRTUAL TABLE", translated)
        self.assertNotIn("CREATE TRIGGER", translated)
        self.assertIn("search_vector tsvector", translated)
        self.assertIn("USING GIN(search_vector)", translated)

    def test_translation_orders_foreign_key_dependencies(self) -> None:
        translated = translate_schema(
            """CREATE TABLE IF NOT EXISTS installation_credentials (
                   operator_id INTEGER REFERENCES operator_accounts(id)
               );
               CREATE TABLE IF NOT EXISTS operator_accounts (
                   id INTEGER PRIMARY KEY
               );"""
        )
        self.assertLess(
            translated.index("CREATE TABLE IF NOT EXISTS operator_accounts"),
            translated.index("CREATE TABLE IF NOT EXISTS installation_credentials"),
        )

    def test_runner_locks_and_records_every_ordered_version(self) -> None:
        raw_connection = mock.MagicMock()
        raw_connection.execute.side_effect = [
            mock.MagicMock(),
            mock.MagicMock(fetchone=mock.Mock(return_value=(True,))),
            mock.MagicMock(fetchone=mock.Mock(return_value=(None,))),
            mock.MagicMock(fetchone=mock.Mock(return_value=(0,))),
        ] + [mock.MagicMock()] * 40
        connection = PostgreSQLConnection(raw_connection)
        migrate_postgresql(connection, "CREATE TABLE sample (id INTEGER PRIMARY KEY);")

        statements = [call.args[0] for call in raw_connection.execute.call_args_list]
        self.assertEqual(statements[0], "SELECT pg_advisory_xact_lock(%s)")
        migration_calls = [
            statement for statement in statements
            if "INSERT INTO schema_migrations" in statement
        ]
        self.assertEqual(len(migration_calls), len(MIGRATION_NAMES))
        self.assertEqual(sum("SELECT setval" in statement for statement in statements), 3)
        self.assertEqual(
            raw_connection.execute.call_args_list[0].args[1],
            (MIGRATION_LOCK_ID,),
        )

    def test_preflight_rejects_unowned_unmanaged_and_conflicting_state(self) -> None:
        connection = mock.MagicMock()
        connection.execute.return_value.fetchone.return_value = (False,)
        with self.assertRaisesRegex(RuntimeError, "must own"):
            _validate_migration_state(connection, MIGRATION_NAMES)

        connection.reset_mock()
        connection.execute.side_effect = [
            mock.MagicMock(fetchone=mock.Mock(return_value=(True,))),
            mock.MagicMock(fetchone=mock.Mock(return_value=(None,))),
            mock.MagicMock(fetchone=mock.Mock(return_value=(1,))),
        ]
        with self.assertRaisesRegex(RuntimeError, "unmanaged"):
            _validate_migration_state(connection, MIGRATION_NAMES)

        connection.reset_mock()
        connection.execute.side_effect = [
            mock.MagicMock(fetchone=mock.Mock(return_value=(True,))),
            mock.MagicMock(fetchone=mock.Mock(return_value=("schema_migrations",))),
            mock.MagicMock(fetchall=mock.Mock(return_value=[(1, "wrong migration")])),
        ]
        with self.assertRaisesRegex(RuntimeError, "history is incompatible"):
            _validate_migration_state(connection, MIGRATION_NAMES)


if __name__ == "__main__":
    unittest.main()