from __future__ import annotations

import re
from collections.abc import Callable, Sequence

from .db_protocol import DatabaseConnection


MIGRATION_LOCK_ID = 7_324_680_441
MIGRATION_NAMES = (
    "processing job leases",
    "canonical identity attribution",
    "intelligence platform P0-P3",
    "community tenancy and professional operations",
    "real-time stream operations and incident command",
    "Discord installation authorization intents",
    "legacy schema convergence",
    "tenant announcement delivery",
    "community onboarding controls",
    "processing lease recovery",
    "identity unlink attribution",
    "moderation provider confirmation",
    "community analytics isolation",
    "operator access lifecycle",
    "strict tenant ownership",
    "provider installation attribution",
    "encrypted Twitch installation onboarding",
    "API client community ownership",
    "community runtime policy",
    "community anti-abuse policy",
    "legacy Twitch onboarding convergence",
    "data subject request community ownership",
    "community profile settings",
    "saved moderation filters",
    "moderation rule lifecycle",
    "tenant slo samples",
    "tenant quotas and fair jobs",
)


def _validate_migration_state(
    connection: DatabaseConnection, migration_names: Sequence[str],
) -> None:
    owns_schema = connection.execute(
        """SELECT nspowner=(SELECT usesysid FROM pg_user WHERE usename=current_user)
           FROM pg_namespace WHERE nspname=current_schema()"""
    ).fetchone()
    if owns_schema is None or not bool(owns_schema[0]):
        raise RuntimeError("PostgreSQL migration role must own the target schema")

    registry = connection.execute(
        "SELECT to_regclass(current_schema() || '.schema_migrations')"
    ).fetchone()
    if registry is None or registry[0] is None:
        table_count = connection.execute(
            """SELECT COUNT(*) FROM information_schema.tables
               WHERE table_schema=current_schema() AND table_type='BASE TABLE'"""
        ).fetchone()
        if table_count is not None and int(table_count[0]) != 0:
            raise RuntimeError("PostgreSQL schema contains unmanaged tables")
        return

    applied = list(connection.execute(
        "SELECT version,name FROM schema_migrations ORDER BY version"
    ).fetchall())
    expected = list(enumerate(migration_names, start=1))
    normalized = [(int(row[0]), str(row[1])) for row in applied]
    if normalized != expected[:len(normalized)]:
        raise RuntimeError("PostgreSQL migration history is incompatible")


def _order_table_statements(schema: str) -> str:
    table_pattern = re.compile(
        r"CREATE TABLE IF NOT EXISTS\s+([a-zA-Z0-9_]+)\s*\(.*?\n\s*\);",
        re.DOTALL,
    )
    matches = list(table_pattern.finditer(schema))
    statements = {match.group(1): match.group(0) for match in matches}
    positions = {match.group(1): index for index, match in enumerate(matches)}
    dependencies = {
        table: {
            dependency
            for dependency in re.findall(r"REFERENCES\s+([a-zA-Z0-9_]+)", statement)
            if dependency in statements and dependency != table
        }
        for table, statement in statements.items()
    }
    ordered: list[str] = []
    remaining = set(statements)
    while remaining:
        ready = sorted(
            (table for table in remaining if not dependencies[table] & remaining),
            key=positions.__getitem__,
        )
        if not ready:
            cycle = ", ".join(sorted(remaining))
            raise ValueError(f"cyclic PostgreSQL table dependencies: {cycle}")
        ordered.extend(ready)
        remaining.difference_update(ready)
    schema_without_tables = table_pattern.sub("", schema)
    return "\n\n".join(statements[table] for table in ordered) + schema_without_tables


def translate_schema(sqlite_schema: str) -> str:
    """Translate the additive canonical schema for PostgreSQL."""
    schema = re.sub(
        r"CREATE VIRTUAL TABLE IF NOT EXISTS observation_fts USING fts5\(.*?\);",
        "",
        sqlite_schema,
        flags=re.DOTALL,
    )
    schema = re.sub(
        r"CREATE TRIGGER IF NOT EXISTS observations_fts_(?:insert|update|delete).*?END;",
        "",
        schema,
        flags=re.DOTALL,
    )
    schema = schema.replace(" BLOB", " BYTEA")
    schema = schema.replace(
        "INTEGER PRIMARY KEY",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    )
    schema = schema.replace(
        "TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP",
        "TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)",
    )
    return _order_table_statements(schema) + """

ALTER TABLE observations ADD COLUMN IF NOT EXISTS search_vector tsvector
    GENERATED ALWAYS AS (to_tsvector('simple', COALESCE(text_raw, ''))) STORED;
CREATE INDEX IF NOT EXISTS idx_observations_search_vector
    ON observations USING GIN(search_vector);
CREATE UNIQUE INDEX IF NOT EXISTS idx_moderation_rules_community_name
    ON moderation_rules(community_id, name);
"""


def migrate_postgresql(
    connection: DatabaseConnection,
    sqlite_schema: str,
    migration_names: Sequence[str] = MIGRATION_NAMES,
    seed: Callable[[DatabaseConnection], None] | None = None,
) -> None:
    try:
        connection.execute("SELECT pg_advisory_xact_lock(%s)", (MIGRATION_LOCK_ID,))
        _validate_migration_state(connection, migration_names)
        connection.execute(translate_schema(sqlite_schema))
        for version, name in enumerate(migration_names, start=1):
            connection.execute(
                """INSERT INTO schema_migrations(version,name)
                   VALUES (%s,%s) ON CONFLICT(version) DO NOTHING""",
                (version, name),
            )
        connection.execute(
            """INSERT INTO organizations(id,name,slug)
               VALUES (1,'Default Organization','default') ON CONFLICT(id) DO NOTHING"""
        )
        connection.execute(
            """INSERT INTO workspaces(id,organization_id,name,slug)
               VALUES (1,1,'Default Workspace','default') ON CONFLICT(id) DO NOTHING"""
        )
        connection.execute(
            """INSERT INTO communities(id,workspace_id,name,slug)
               VALUES (1,1,'Default Community','default') ON CONFLICT(id) DO NOTHING"""
        )
        connection.execute(
            """INSERT INTO community_policy_settings(community_id)
               VALUES (1) ON CONFLICT(community_id) DO NOTHING"""
        )
        for table in ("organizations", "workspaces", "communities"):
            connection.execute(
                f"""SELECT setval(
                        pg_get_serial_sequence('{table}','id'),
                        GREATEST((SELECT COALESCE(MAX(id),1) FROM {table}),1),
                        true
                    )"""
            )
        if seed is not None:
            seed(connection)
        connection.commit()
    except Exception:
        connection.rollback()
        raise