CREATE TABLE IF NOT EXISTS organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    primary_display_name TEXT NOT NULL,
    current_reputation_score INTEGER NOT NULL DEFAULT 500,
    candidate_flag INTEGER NOT NULL DEFAULT 0,
    score_confidence REAL NOT NULL DEFAULT 0.0,
    score_model_version INTEGER,
    score_calculated_at TEXT,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS operator_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_user_id TEXT NOT NULL UNIQUE,
    discord_username TEXT NOT NULL,
    role TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','disabled')),
    session_version INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS command_definitions (
    command_name TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    description_template TEXT NOT NULL,
    footer_template TEXT,
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS simple_command_definitions (
    command_name TEXT PRIMARY KEY,
    response_template TEXT NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS discord_channels (
    channel_id TEXT PRIMARY KEY,
    guild_id TEXT NOT NULL,
    channel_name TEXT NOT NULL,
    channel_type INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS twitch_live_announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    twitch_channel_name TEXT NOT NULL,
    twitch_stream_id TEXT NOT NULL,
    discord_guild_id TEXT NOT NULL,
    discord_channel_id TEXT NOT NULL,
    announced_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(twitch_channel_name, twitch_stream_id, discord_guild_id)
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_type TEXT NOT NULL,
    actor_id INTEGER,
    action_type TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id INTEGER,
    payload_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS metrics_rollups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_name TEXT NOT NULL,
    bucket_start TEXT NOT NULL,
    bucket_size TEXT NOT NULL,
    dimension_json TEXT NOT NULL DEFAULT '{}',
    value REAL NOT NULL,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(metric_name, bucket_start, bucket_size, dimension_json)
);

CREATE TABLE IF NOT EXISTS service_reliability_buckets (
    service_name TEXT NOT NULL,
    bucket_start TEXT NOT NULL,
    is_up INTEGER NOT NULL,
    status TEXT NOT NULL,
    recorded_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    PRIMARY KEY(service_name, bucket_start)
);

CREATE TABLE IF NOT EXISTS role_heartbeats (
    role TEXT PRIMARY KEY,
    status TEXT NOT NULL,
    detail_json TEXT NOT NULL DEFAULT '{}',
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS processing_job_ownership (
    job_type TEXT PRIMARY KEY,
    owner_runtime TEXT NOT NULL DEFAULT 'python'
        CHECK(owner_runtime IN ('python', 'deno', 'none')),
    shadow_runtime TEXT
        CHECK(shadow_runtime IN ('python', 'deno') OR shadow_runtime IS NULL),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS saved_queries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id INTEGER,
    name TEXT NOT NULL,
    query_text TEXT NOT NULL DEFAULT '',
    filters_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(operator_id, name)
);

CREATE TABLE IF NOT EXISTS external_feed_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key TEXT NOT NULL UNIQUE,
    display_name TEXT NOT NULL,
    source_type TEXT NOT NULL,
    trust_weight REAL NOT NULL DEFAULT 0.5,
    enabled INTEGER NOT NULL DEFAULT 1,
    configuration_json TEXT NOT NULL DEFAULT '{}',
    last_observed_at TEXT,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS cohort_baselines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cohort_type TEXT NOT NULL,
    cohort_key TEXT NOT NULL,
    signal_key TEXT NOT NULL,
    sample_size INTEGER NOT NULL,
    mean_value REAL NOT NULL,
    stddev_value REAL NOT NULL,
    median_value REAL NOT NULL,
    p90_value REAL NOT NULL,
    calculated_at TEXT NOT NULL,
    UNIQUE(cohort_type, cohort_key, signal_key)
);

CREATE TABLE IF NOT EXISTS model_evaluation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_key TEXT NOT NULL,
    model_version INTEGER NOT NULL,
    sample_size INTEGER NOT NULL,
    metrics_json TEXT NOT NULL,
    score_distribution_json TEXT NOT NULL,
    calculated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS schema_migrations (
    version BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    applied_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS operational_metrics (
    metric_name TEXT NOT NULL,
    dimension_key TEXT NOT NULL DEFAULT '',
    value REAL NOT NULL,
    observed_at TEXT NOT NULL,
    PRIMARY KEY(metric_name, dimension_key, observed_at)
);

CREATE TABLE IF NOT EXISTS model_registry (
    model_key TEXT NOT NULL,
    version INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'shadow',
    description TEXT NOT NULL,
    minimum_precision REAL,
    approved_by_operator_id INTEGER,
    approved_at TEXT,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    PRIMARY KEY(model_key, version)
);

CREATE TABLE IF NOT EXISTS raid_playbooks (
    playbook_key TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'high',
    steps_json TEXT NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1,
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS workspaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(organization_id, slug)
);

CREATE TABLE IF NOT EXISTS platform_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform TEXT NOT NULL,
    platform_user_id TEXT NOT NULL,
    username TEXT NOT NULL,
    guild_or_channel_context TEXT,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    detached_from_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(platform, platform_user_id)
);

CREATE TABLE IF NOT EXISTS operator_discord_guild_permissions (
    operator_id INTEGER NOT NULL REFERENCES operator_accounts(id) ON DELETE CASCADE,
    guild_id TEXT NOT NULL,
    guild_name TEXT,
    permissions BIGINT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    PRIMARY KEY(operator_id, guild_id)
);

ALTER TABLE operator_discord_guild_permissions
    ADD COLUMN IF NOT EXISTS guild_name TEXT;

ALTER TABLE operator_discord_guild_permissions
    ALTER COLUMN permissions TYPE BIGINT USING permissions::BIGINT;

CREATE TABLE IF NOT EXISTS reputation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    source_type TEXT NOT NULL,
    source_id INTEGER,
    delta INTEGER NOT NULL,
    reason_code TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS derived_signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    signal_key TEXT NOT NULL,
    analyzer_version INTEGER NOT NULL,
    value_real REAL NOT NULL,
    value_json TEXT NOT NULL DEFAULT '{}',
    confidence REAL NOT NULL,
    evidence_count INTEGER NOT NULL,
    window_start TEXT,
    window_end TEXT,
    calculated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(user_id, signal_key, analyzer_version),
    CHECK(confidence >= 0.0 AND confidence <= 1.0),
    CHECK(evidence_count >= 0)
);

CREATE TABLE IF NOT EXISTS derived_signal_windows (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    signal_key TEXT NOT NULL,
    window_name TEXT NOT NULL,
    analyzer_version INTEGER NOT NULL,
    value_real REAL NOT NULL,
    value_json TEXT NOT NULL DEFAULT '{}',
    confidence REAL NOT NULL,
    evidence_count INTEGER NOT NULL,
    window_start TEXT,
    window_end TEXT,
    calculated_at TEXT NOT NULL,
    PRIMARY KEY(user_id, signal_key, window_name, analyzer_version)
);

CREATE TABLE IF NOT EXISTS graph_metrics (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    in_degree REAL NOT NULL,
    out_degree REAL NOT NULL,
    weighted_degree REAL NOT NULL,
    betweenness REAL NOT NULL,
    pagerank REAL NOT NULL,
    cluster_id INTEGER,
    is_bridge INTEGER NOT NULL DEFAULT 0,
    influence_score REAL NOT NULL,
    calculated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS graph_metric_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    in_degree REAL NOT NULL,
    out_degree REAL NOT NULL,
    weighted_degree REAL NOT NULL,
    betweenness REAL NOT NULL,
    pagerank REAL NOT NULL,
    cluster_id INTEGER,
    is_bridge INTEGER NOT NULL DEFAULT 0,
    influence_score REAL NOT NULL,
    calculated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS cohort_anomalies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    cohort_type TEXT NOT NULL,
    cohort_key TEXT NOT NULL,
    signal_key TEXT NOT NULL,
    observed_value REAL NOT NULL,
    baseline_mean REAL NOT NULL,
    z_score REAL NOT NULL,
    direction TEXT NOT NULL,
    confidence REAL NOT NULL,
    calculated_at TEXT NOT NULL,
    UNIQUE(user_id, cohort_type, cohort_key, signal_key)
);

CREATE TABLE IF NOT EXISTS threshold_backtests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_run_id INTEGER NOT NULL REFERENCES model_evaluation_runs(id) ON DELETE CASCADE,
    threshold REAL NOT NULL,
    true_positive INTEGER NOT NULL,
    false_positive INTEGER NOT NULL,
    true_negative INTEGER NOT NULL,
    false_negative INTEGER NOT NULL,
    precision REAL NOT NULL,
    recall REAL NOT NULL,
    false_positive_rate REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS communities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id INTEGER NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    timezone TEXT NOT NULL DEFAULT 'UTC',
    locale TEXT NOT NULL DEFAULT 'en-US',
    description TEXT NOT NULL DEFAULT '',
    guidelines TEXT NOT NULL DEFAULT '',
    notifications_enabled INTEGER NOT NULL DEFAULT 1,
    retention_days INTEGER NOT NULL DEFAULT 90,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(workspace_id, slug)
);

CREATE TABLE IF NOT EXISTS server_boost_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform TEXT NOT NULL,
    channel_id TEXT NOT NULL,
    requester_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    requester_platform_account_id INTEGER NOT NULL REFERENCES platform_accounts(id) ON DELETE CASCADE,
    command_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    requested_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    fulfilled_at TEXT
);

CREATE TABLE IF NOT EXISTS identity_link_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    left_platform_account_id INTEGER NOT NULL REFERENCES platform_accounts(id) ON DELETE CASCADE,
    right_platform_account_id INTEGER NOT NULL REFERENCES platform_accounts(id) ON DELETE CASCADE,
    confidence REAL NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    evidence_json TEXT NOT NULL DEFAULT '{}',
    model_version INTEGER NOT NULL,
    reviewed_by_operator_id INTEGER,
    reviewed_at TEXT,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(left_platform_account_id, right_platform_account_id, model_version),
    CHECK(left_platform_account_id < right_platform_account_id),
    CHECK(status IN ('pending', 'approved', 'rejected', 'expired'))
);

CREATE TABLE IF NOT EXISTS community_installations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    platform TEXT NOT NULL,
    external_community_id TEXT NOT NULL,
    display_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    scopes_json TEXT NOT NULL DEFAULT '[]',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    capabilities_json TEXT NOT NULL DEFAULT '[]',
    health_status TEXT NOT NULL DEFAULT 'unknown',
    last_health_check_at TEXT,
    reconnect_attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    token_reference TEXT,
    last_verified_at TEXT,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(platform, external_community_id)
);

CREATE TABLE IF NOT EXISTS twitch_install_intents (
    nonce TEXT PRIMARY KEY,
    operator_id INTEGER NOT NULL REFERENCES operator_accounts(id) ON DELETE CASCADE,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    broadcaster_login TEXT NOT NULL,
    scopes_json TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    consumed_at TEXT,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS operator_community_roles (
    operator_id INTEGER NOT NULL REFERENCES operator_accounts(id) ON DELETE CASCADE,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    PRIMARY KEY(operator_id, community_id)
);

CREATE TABLE IF NOT EXISTS operator_permission_overrides (
    operator_id INTEGER NOT NULL REFERENCES operator_accounts(id) ON DELETE CASCADE,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    permission TEXT NOT NULL,
    decision TEXT NOT NULL CHECK(decision IN ('grant', 'deny')),
    updated_by_operator_id INTEGER REFERENCES operator_accounts(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    PRIMARY KEY(operator_id, community_id, permission)
);

CREATE TABLE IF NOT EXISTS operator_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    target_discord_user_id TEXT NOT NULL,
    invited_role TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK(status IN ('pending','accepted','revoked','expired')),
    expires_at TEXT NOT NULL,
    invited_by_operator_id INTEGER NOT NULL REFERENCES operator_accounts(id),
    accepted_by_operator_id INTEGER REFERENCES operator_accounts(id),
    accepted_at TEXT,
    revoked_at TEXT,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS discord_install_intents (
    nonce TEXT PRIMARY KEY,
    operator_id INTEGER NOT NULL REFERENCES operator_accounts(id) ON DELETE CASCADE,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    guild_id TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    consumed_at TEXT,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS pilot_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    code_hash TEXT NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    created_by_operator_id INTEGER REFERENCES operator_accounts(id) ON DELETE SET NULL,
    consumed_by_operator_id INTEGER REFERENCES operator_accounts(id) ON DELETE SET NULL,
    consumed_at TEXT,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS moderation_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    rule_type TEXT NOT NULL,
    pattern TEXT NOT NULL,
    severity TEXT NOT NULL,
    auto_enforce_action TEXT,
    enforcement_mode TEXT NOT NULL DEFAULT 'enforce',
    action_duration_seconds INTEGER NOT NULL DEFAULT 600,
    platform_scope_json TEXT NOT NULL DEFAULT '["discord","twitch"]',
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS user_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    operator_id INTEGER NOT NULL,
    body TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS member_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    reporter_platform_account_id INTEGER REFERENCES platform_accounts(id),
    subject_platform_account_id INTEGER NOT NULL REFERENCES platform_accounts(id),
    category TEXT NOT NULL,
    summary TEXT NOT NULL,
    evidence_json TEXT NOT NULL DEFAULT '{}',
    severity TEXT NOT NULL DEFAULT 'medium',
    status TEXT NOT NULL DEFAULT 'open',
    assigned_operator_id INTEGER REFERENCES operator_accounts(id),
    resolution TEXT,
    resolution_note TEXT NOT NULL DEFAULT '',
    resolved_by_operator_id INTEGER REFERENCES operator_accounts(id),
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    resolved_at TEXT
);

CREATE TABLE IF NOT EXISTS tenant_slo_samples (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    metric_name TEXT NOT NULL,
    value REAL NOT NULL,
    target_value REAL NOT NULL,
    status TEXT NOT NULL,
    details_json TEXT NOT NULL DEFAULT '{}',
    observed_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS tenant_quota_policies (
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    quota_type TEXT NOT NULL,
    limit_count INTEGER NOT NULL,
    window_seconds INTEGER NOT NULL DEFAULT 60,
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    PRIMARY KEY(community_id, quota_type)
);

CREATE TABLE IF NOT EXISTS tenant_quota_usage (
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    quota_type TEXT NOT NULL,
    window_start TEXT NOT NULL,
    usage_count INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY(community_id, quota_type, window_start)
);

CREATE TABLE IF NOT EXISTS tenant_job_schedule (
    community_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY REFERENCES communities(id) ON DELETE CASCADE,
    last_claim_sequence INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS community_derived_signal_windows (
    community_id INTEGER NOT NULL REFERENCES communities(id),
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    signal_key TEXT NOT NULL,
    window_name TEXT NOT NULL,
    analyzer_version INTEGER NOT NULL,
    value_real REAL NOT NULL,
    value_json TEXT NOT NULL DEFAULT '{}',
    confidence REAL NOT NULL,
    evidence_count INTEGER NOT NULL,
    window_start TEXT,
    window_end TEXT,
    calculated_at TEXT NOT NULL,
    PRIMARY KEY(community_id, user_id, signal_key, window_name, analyzer_version)
);

CREATE TABLE IF NOT EXISTS investigation_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    title TEXT NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    priority TEXT NOT NULL DEFAULT 'medium',
    status TEXT NOT NULL DEFAULT 'open',
    owner_operator_id INTEGER,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    closed_at TEXT
);

CREATE TABLE IF NOT EXISTS entity_relationships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    source_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    target_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    relationship_type TEXT NOT NULL,
    context_key TEXT NOT NULL DEFAULT '',
    strength REAL NOT NULL DEFAULT 0,
    evidence_count INTEGER NOT NULL DEFAULT 0,
    first_observed_at TEXT NOT NULL,
    last_observed_at TEXT NOT NULL,
    evidence_json TEXT NOT NULL DEFAULT '{}',
    UNIQUE(community_id, source_user_id, target_user_id, relationship_type, context_key)
);

CREATE TABLE IF NOT EXISTS intelligence_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    report_type TEXT NOT NULL,
    subject_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    content_json TEXT NOT NULL,
    evidence_json TEXT NOT NULL DEFAULT '[]',
    generated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    generator_version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS moderation_saved_filters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    operator_id INTEGER NOT NULL REFERENCES operator_accounts(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    filters_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(community_id, operator_id, name)
);

CREATE TABLE IF NOT EXISTS emerging_topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    topic_key TEXT NOT NULL UNIQUE,
    topic_kind TEXT NOT NULL,
    label TEXT NOT NULL,
    current_count INTEGER NOT NULL,
    baseline_rate REAL NOT NULL,
    velocity REAL NOT NULL,
    context_count INTEGER NOT NULL,
    community_count INTEGER NOT NULL,
    unusualness REAL NOT NULL,
    first_observed_at TEXT,
    last_observed_at TEXT,
    details_json TEXT NOT NULL DEFAULT '{}',
    calculated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS topic_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    topic_key TEXT NOT NULL,
    topic_kind TEXT NOT NULL,
    current_count INTEGER NOT NULL,
    baseline_rate REAL NOT NULL,
    velocity REAL NOT NULL,
    context_count INTEGER NOT NULL,
    community_count INTEGER NOT NULL,
    unusualness REAL NOT NULL,
    calculated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS community_graph_metrics (
    community_id INTEGER NOT NULL REFERENCES communities(id),
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    in_degree REAL NOT NULL,
    out_degree REAL NOT NULL,
    weighted_degree REAL NOT NULL,
    betweenness REAL NOT NULL,
    pagerank REAL NOT NULL,
    cluster_id INTEGER,
    is_bridge INTEGER NOT NULL DEFAULT 0,
    influence_score REAL NOT NULL,
    calculated_at TEXT NOT NULL,
    PRIMARY KEY (community_id, user_id)
);

CREATE TABLE IF NOT EXISTS community_graph_metric_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    in_degree REAL NOT NULL,
    out_degree REAL NOT NULL,
    weighted_degree REAL NOT NULL,
    betweenness REAL NOT NULL,
    pagerank REAL NOT NULL,
    cluster_id INTEGER,
    is_bridge INTEGER NOT NULL DEFAULT 0,
    influence_score REAL NOT NULL,
    calculated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS community_identity_link_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    left_platform_account_id INTEGER NOT NULL REFERENCES platform_accounts(id) ON DELETE CASCADE,
    right_platform_account_id INTEGER NOT NULL REFERENCES platform_accounts(id) ON DELETE CASCADE,
    confidence REAL NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    evidence_json TEXT NOT NULL DEFAULT '{}',
    model_version INTEGER NOT NULL,
    reviewed_by_operator_id INTEGER,
    reviewed_at TEXT,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(community_id, left_platform_account_id, right_platform_account_id, model_version),
    CHECK(left_platform_account_id < right_platform_account_id),
    CHECK(status IN ('pending', 'approved', 'rejected', 'expired'))
);

CREATE TABLE IF NOT EXISTS community_cohort_baselines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    cohort_type TEXT NOT NULL,
    cohort_key TEXT NOT NULL,
    signal_key TEXT NOT NULL,
    sample_size INTEGER NOT NULL,
    mean_value REAL NOT NULL,
    stddev_value REAL NOT NULL,
    median_value REAL NOT NULL,
    p90_value REAL NOT NULL,
    calculated_at TEXT NOT NULL,
    UNIQUE(community_id, cohort_type, cohort_key, signal_key)
);

CREATE TABLE IF NOT EXISTS community_cohort_anomalies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    cohort_type TEXT NOT NULL,
    cohort_key TEXT NOT NULL,
    signal_key TEXT NOT NULL,
    observed_value REAL NOT NULL,
    baseline_mean REAL NOT NULL,
    z_score REAL NOT NULL,
    direction TEXT NOT NULL,
    confidence REAL NOT NULL,
    calculated_at TEXT NOT NULL,
    UNIQUE(community_id, user_id, cohort_type, cohort_key, signal_key)
);

CREATE TABLE IF NOT EXISTS community_memberships (
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    platform_account_id INTEGER NOT NULL REFERENCES platform_accounts(id) ON DELETE CASCADE,
    role TEXT NOT NULL DEFAULT 'member',
    joined_at TEXT,
    left_at TEXT,
    attributes_json TEXT NOT NULL DEFAULT '{}',
    PRIMARY KEY(community_id, platform_account_id)
);

CREATE TABLE IF NOT EXISTS community_policy_settings (
    community_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY REFERENCES communities(id) ON DELETE CASCADE,
    moderation_shadow_mode INTEGER NOT NULL DEFAULT 1,
    automatic_enforcement_enabled INTEGER NOT NULL DEFAULT 0,
    allow_bot_messages INTEGER NOT NULL DEFAULT 0,
    anti_abuse_enabled INTEGER NOT NULL DEFAULT 1,
    anti_abuse_enforcement_mode TEXT NOT NULL DEFAULT 'shadow',
    message_burst_limit INTEGER NOT NULL DEFAULT 12 CHECK(message_burst_limit > 1),
    message_burst_window_seconds INTEGER NOT NULL DEFAULT 10 CHECK(message_burst_window_seconds > 0),
    mention_limit INTEGER NOT NULL DEFAULT 8 CHECK(mention_limit > 0),
    join_raid_limit INTEGER NOT NULL DEFAULT 25 CHECK(join_raid_limit > 1),
    join_raid_window_seconds INTEGER NOT NULL DEFAULT 60 CHECK(join_raid_window_seconds > 0),
    message_retention_days INTEGER NOT NULL DEFAULT 90 CHECK(message_retention_days > 0),
    analytics_retention_days INTEGER NOT NULL DEFAULT 90 CHECK(analytics_retention_days > 0),
    model_thresholds_json TEXT NOT NULL DEFAULT '{}',
    sharing_policy TEXT NOT NULL DEFAULT 'isolated',
    updated_by_operator_id INTEGER,
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS intelligence_sharing_agreements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    target_community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'pending',
    allowed_finding_types_json TEXT NOT NULL DEFAULT '[]',
    expires_at TEXT,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(source_community_id, target_community_id)
);

CREATE TABLE IF NOT EXISTS replay_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    requested_by_operator_id INTEGER,
    event_type TEXT,
    start_at TEXT,
    end_at TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    replayed_count INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    completed_at TEXT
);

CREATE TABLE IF NOT EXISTS community_intelligence_profiles (
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    profile_version INTEGER NOT NULL,
    trust_score REAL NOT NULL,
    risk_score REAL NOT NULL,
    engagement_score REAL NOT NULL,
    identity_confidence REAL NOT NULL,
    maturity_score REAL NOT NULL,
    confidence REAL NOT NULL,
    evidence_count INTEGER NOT NULL,
    explanation_json TEXT NOT NULL DEFAULT '{}',
    calculated_at TEXT NOT NULL,
    PRIMARY KEY(community_id, user_id, profile_version)
);

CREATE TABLE IF NOT EXISTS coordination_campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    campaign_key TEXT NOT NULL,
    campaign_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    severity TEXT NOT NULL DEFAULT 'medium',
    message_count INTEGER NOT NULL DEFAULT 0,
    actor_count INTEGER NOT NULL DEFAULT 0,
    confidence REAL NOT NULL DEFAULT 0.0,
    first_observed_at TEXT NOT NULL,
    last_observed_at TEXT NOT NULL,
    details_json TEXT NOT NULL DEFAULT '{}',
    UNIQUE(community_id, campaign_key)
);

CREATE TABLE IF NOT EXISTS data_subject_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    request_type TEXT NOT NULL,
    platform TEXT,
    platform_user_id TEXT,
    status TEXT NOT NULL DEFAULT 'open',
    requested_by_operator_id INTEGER REFERENCES operator_accounts(id) ON DELETE SET NULL,
    completed_by_operator_id INTEGER REFERENCES operator_accounts(id) ON DELETE SET NULL,
    requested_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    completed_at TEXT,
    result_json TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS twitch_eventsub_subscriptions (
    subscription_id TEXT PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    subscription_type TEXT NOT NULL,
    subscription_version TEXT NOT NULL,
    condition_json TEXT NOT NULL,
    transport_method TEXT NOT NULL,
    status TEXT NOT NULL,
    callback_url TEXT,
    cost INTEGER NOT NULL DEFAULT 0,
    last_event_at TEXT,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS api_clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    key_hash TEXT NOT NULL UNIQUE,
    scopes_json TEXT NOT NULL DEFAULT '[]',
    status TEXT NOT NULL DEFAULT 'active',
    rate_limit_per_minute INTEGER NOT NULL DEFAULT 120,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    revoked_at TEXT
);

CREATE TABLE IF NOT EXISTS moderation_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    lead_operator_id INTEGER REFERENCES operator_accounts(id) ON DELETE SET NULL,
    incoming_operator_id INTEGER REFERENCES operator_accounts(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'active',
    started_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    ended_at TEXT,
    handoff_note TEXT NOT NULL DEFAULT '',
    handoff_at TEXT
);

CREATE TABLE IF NOT EXISTS moderation_shift_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    operator_id INTEGER NOT NULL REFERENCES operator_accounts(id) ON DELETE CASCADE,
    starts_at TEXT NOT NULL,
    ends_at TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'scheduled' CHECK(status IN ('scheduled','active','completed','cancelled')),
    created_by_operator_id INTEGER REFERENCES operator_accounts(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS twitch_control_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    operator_id INTEGER REFERENCES operator_accounts(id) ON DELETE SET NULL,
    broadcaster_id TEXT NOT NULL,
    control_type TEXT NOT NULL,
    requested_json TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    provider_status TEXT,
    provider_response_json TEXT NOT NULL DEFAULT '{}',
    requested_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    confirmed_at TEXT,
    error_message TEXT
);

CREATE TABLE IF NOT EXISTS notification_destinations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    destination_type TEXT NOT NULL,
    name TEXT NOT NULL,
    target TEXT NOT NULL,
    minimum_severity TEXT NOT NULL DEFAULT 'high',
    enabled INTEGER NOT NULL DEFAULT 1,
    secret_reference TEXT,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS community_onboarding_resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    resource_url TEXT NOT NULL,
    message_template TEXT NOT NULL DEFAULT '{mention}: {title} - {resource_url}',
    enabled INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_by_operator_id INTEGER REFERENCES operator_accounts(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS audience_edges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    source_key TEXT NOT NULL,
    target_key TEXT NOT NULL,
    edge_type TEXT NOT NULL,
    weight REAL NOT NULL DEFAULT 1.0,
    event_count INTEGER NOT NULL DEFAULT 1,
    first_observed_at TEXT NOT NULL,
    last_observed_at TEXT NOT NULL,
    evidence_json TEXT NOT NULL DEFAULT '{}',
    UNIQUE(community_id, source_key, target_key, edge_type)
);

CREATE TABLE IF NOT EXISTS installation_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    installation_id INTEGER NOT NULL UNIQUE
        REFERENCES community_installations(id) ON DELETE CASCADE,
    access_token_ciphertext BYTEA NOT NULL,
    refresh_token_ciphertext BYTEA,
    scopes_json TEXT NOT NULL DEFAULT '[]',
    key_version INTEGER NOT NULL DEFAULT 1,
    rotation_count INTEGER NOT NULL DEFAULT 1,
    rotated_at TEXT,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS installation_runtime_leases (
    installation_id INTEGER PRIMARY KEY
        REFERENCES community_installations(id) ON DELETE CASCADE,
    owner_runtime TEXT NOT NULL DEFAULT 'python'
        CHECK(owner_runtime IN ('python', 'deno', 'none')),
    lease_holder TEXT,
    lease_acquired_at TEXT,
    lease_expires_at TEXT,
    last_renewed_at TEXT,
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    CHECK(
        (lease_holder IS NULL AND lease_expires_at IS NULL) OR
        (lease_holder IS NOT NULL AND lease_expires_at IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_installation_runtime_leases_expiry
    ON installation_runtime_leases(owner_runtime, lease_expires_at);

CREATE TABLE IF NOT EXISTS installation_health_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    installation_id INTEGER NOT NULL REFERENCES community_installations(id) ON DELETE CASCADE,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    health_status TEXT NOT NULL,
    lifecycle_status TEXT NOT NULL,
    reconnect_attempted INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    checked_at TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS moderation_rule_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    moderation_rule_id INTEGER NOT NULL REFERENCES moderation_rules(id) ON DELETE CASCADE,
    version_number INTEGER NOT NULL,
    lifecycle_state TEXT NOT NULL,
    config_json TEXT NOT NULL,
    impact_json TEXT NOT NULL DEFAULT '{}',
    created_by_operator_id INTEGER NOT NULL REFERENCES operator_accounts(id),
    approved_by_operator_id INTEGER REFERENCES operator_accounts(id),
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    approved_at TEXT,
    UNIQUE(moderation_rule_id, version_number)
);

CREATE TABLE IF NOT EXISTS moderation_rule_exemptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    moderation_rule_id INTEGER NOT NULL REFERENCES moderation_rules(id) ON DELETE CASCADE,
    exemption_type TEXT NOT NULL,
    exemption_value TEXT NOT NULL,
    reason TEXT NOT NULL,
    created_by_operator_id INTEGER NOT NULL REFERENCES operator_accounts(id),
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(community_id, moderation_rule_id, exemption_type, exemption_value)
);

CREATE TABLE IF NOT EXISTS observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform TEXT NOT NULL,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    installation_id INTEGER REFERENCES community_installations(id) ON DELETE SET NULL,
    event_type TEXT NOT NULL,
    external_event_id TEXT,
    actor_platform_account_id INTEGER
        REFERENCES platform_accounts(id) ON DELETE SET NULL,
    target_platform_account_id INTEGER
        REFERENCES platform_accounts(id) ON DELETE SET NULL,
    container_id TEXT,
    context_id TEXT,
    text_raw TEXT,
    attributes_json TEXT NOT NULL DEFAULT '{}',
    raw_payload_json TEXT NOT NULL DEFAULT '{}',
    occurred_at TEXT NOT NULL,
    ingested_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    schema_version INTEGER NOT NULL DEFAULT 1,

    UNIQUE(platform, event_type, external_event_id)
);

CREATE TABLE IF NOT EXISTS case_entities (
    case_id INTEGER NOT NULL REFERENCES investigation_cases(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role TEXT NOT NULL DEFAULT 'subject',
    added_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    PRIMARY KEY(case_id, user_id)
);

CREATE TABLE IF NOT EXISTS case_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id INTEGER NOT NULL REFERENCES investigation_cases(id) ON DELETE CASCADE,
    operator_id INTEGER,
    activity_type TEXT NOT NULL,
    body TEXT NOT NULL DEFAULT '',
    payload_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS legal_holds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    case_id INTEGER REFERENCES investigation_cases(id) ON DELETE SET NULL,
    reason TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    created_by_operator_id INTEGER,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    released_at TEXT
);

CREATE TABLE IF NOT EXISTS api_request_usage (
    api_client_id INTEGER NOT NULL REFERENCES api_clients(id) ON DELETE CASCADE,
    minute_bucket TEXT NOT NULL,
    request_count INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY(api_client_id, minute_bucket)
);

CREATE TABLE IF NOT EXISTS community_announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    target_installation_id INTEGER REFERENCES community_installations(id) ON DELETE CASCADE,
    platform TEXT NOT NULL,
    target_external_id TEXT NOT NULL,
    body TEXT NOT NULL,
    dedupe_key TEXT,
    source_json TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'draft',
    scheduled_at TEXT,
    timezone TEXT NOT NULL DEFAULT 'UTC',
    created_by_operator_id INTEGER REFERENCES operator_accounts(id) ON DELETE SET NULL,
    approved_by_operator_id INTEGER REFERENCES operator_accounts(id) ON DELETE SET NULL,
    approved_at TEXT,
    delivered_at TEXT,
    last_error TEXT,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS community_onboarding_settings (
    community_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY REFERENCES communities(id) ON DELETE CASCADE,
    discord_installation_id INTEGER REFERENCES community_installations(id) ON DELETE CASCADE,
    welcome_channel_id TEXT,
    welcome_template TEXT NOT NULL DEFAULT 'Welcome {mention} to the community!',
    welcome_enabled INTEGER NOT NULL DEFAULT 0,
    newcomer_role_id TEXT,
    newcomer_role_enabled INTEGER NOT NULL DEFAULT 0,
    checkpoint_due_hours INTEGER NOT NULL DEFAULT 24,
    checkpoint_reminder_enabled INTEGER NOT NULL DEFAULT 0,
    checkpoint_reminder_template TEXT NOT NULL DEFAULT 'Reminder {mention}: please complete community verification.',
    verification_resource_enabled INTEGER NOT NULL DEFAULT 0,
    verification_resource_url TEXT,
    verification_resource_template TEXT NOT NULL DEFAULT 'You are verified, {mention}. Community resources: {resource_url}',
    verification_evidence_required INTEGER NOT NULL DEFAULT 0,
    self_service_verification_enabled INTEGER NOT NULL DEFAULT 0,
    updated_by_operator_id INTEGER REFERENCES operator_accounts(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS community_onboarding_members (
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    discord_installation_id INTEGER NOT NULL REFERENCES community_installations(id) ON DELETE CASCADE,
    platform_user_id TEXT NOT NULL,
    username TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'newcomer',
    newcomer_role_id TEXT,
    role_assignment_status TEXT NOT NULL DEFAULT 'disabled',
    role_assignment_attempts INTEGER NOT NULL DEFAULT 0,
    role_assignment_error TEXT,
    joined_at TEXT NOT NULL,
    checkpoint_due_at TEXT,
    reminder_sent_at TEXT,
    verification_evidence TEXT,
    verified_at TEXT,
    verified_by_operator_id INTEGER REFERENCES operator_accounts(id) ON DELETE SET NULL,
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    PRIMARY KEY(community_id, platform_user_id)
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    observation_id INTEGER REFERENCES observations(id) ON DELETE SET NULL,
    installation_id INTEGER REFERENCES community_installations(id) ON DELETE SET NULL,
    platform TEXT NOT NULL,
    platform_message_id TEXT,
    platform_account_id INTEGER NOT NULL REFERENCES platform_accounts(id),
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    channel_id TEXT NOT NULL,
    content_raw TEXT NOT NULL,
    content_normalized TEXT NOT NULL,
    sent_at TEXT NOT NULL,
    edited_at TEXT,
    deleted_at TEXT,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(platform, platform_message_id)
);

CREATE TABLE IF NOT EXISTS processing_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER REFERENCES communities(id) ON DELETE CASCADE,
    stage TEXT NOT NULL,
    job_type TEXT NOT NULL,
    observation_id INTEGER REFERENCES observations(id) ON DELETE CASCADE,
    payload_json TEXT NOT NULL DEFAULT '{}',

    status TEXT NOT NULL DEFAULT 'pending',
    priority INTEGER NOT NULL DEFAULT 100,
    attempts INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 5,

    available_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    claimed_at TEXT,
    claimed_by TEXT,
    lease_expires_at TEXT,
    completed_at TEXT,
    last_error TEXT,

    idempotency_key TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),

    CHECK(stage IN ('analysis', 'action')),
    CHECK(status IN (
        'pending',
        'running',
        'completed',
        'retry',
        'failed',
        'cancelled'
    ))
);

CREATE TABLE IF NOT EXISTS command_analysis_results (
    observation_id INTEGER NOT NULL
        REFERENCES observations(id) ON DELETE CASCADE,
    analyzer_version INTEGER NOT NULL,
    command_name TEXT,
    matched INTEGER NOT NULL,
    rendered_payload_json TEXT,
    analyzed_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),

    PRIMARY KEY (observation_id, analyzer_version),

    CHECK (matched IN (0, 1))
);

CREATE TABLE IF NOT EXISTS signal_calculation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    trigger_observation_id INTEGER REFERENCES observations(id) ON DELETE SET NULL,
    analyzer_version INTEGER NOT NULL,
    calculated_at TEXT NOT NULL,
    UNIQUE(user_id, trigger_observation_id, analyzer_version)
);

CREATE TABLE IF NOT EXISTS community_signal_calculation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    trigger_observation_id INTEGER REFERENCES observations(id) ON DELETE SET NULL,
    analyzer_version INTEGER NOT NULL,
    calculated_at TEXT NOT NULL,
    UNIQUE(community_id, user_id, trigger_observation_id, analyzer_version)
);

CREATE TABLE IF NOT EXISTS relationship_evidence (
    relationship_id INTEGER NOT NULL REFERENCES entity_relationships(id) ON DELETE CASCADE,
    observation_id INTEGER NOT NULL REFERENCES observations(id) ON DELETE CASCADE,
    occurred_at TEXT NOT NULL,
    weight REAL NOT NULL DEFAULT 1.0,
    attributes_json TEXT NOT NULL DEFAULT '{}',
    PRIMARY KEY(relationship_id, observation_id)
);

CREATE TABLE IF NOT EXISTS stream_states (
    platform TEXT NOT NULL,
    stream_key TEXT NOT NULL,
    status TEXT NOT NULL,
    title TEXT,
    category TEXT,
    started_at TEXT,
    ended_at TEXT,
    latest_observation_id INTEGER REFERENCES observations(id) ON DELETE SET NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY(platform, stream_key)
);

CREATE TABLE IF NOT EXISTS content_analysis (
    observation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY REFERENCES observations(id) ON DELETE CASCADE,
    analyzer_version INTEGER NOT NULL,
    language_code TEXT NOT NULL,
    language_confidence REAL NOT NULL,
    sentiment_label TEXT NOT NULL,
    sentiment_score REAL NOT NULL,
    intent_label TEXT NOT NULL,
    intent_confidence REAL NOT NULL,
    threat_level TEXT NOT NULL,
    threat_score REAL NOT NULL,
    conversation_json TEXT NOT NULL DEFAULT '{}',
    indicators_json TEXT NOT NULL DEFAULT '[]',
    analyzed_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS content_entities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    observation_id INTEGER NOT NULL REFERENCES observations(id) ON DELETE CASCADE,
    entity_type TEXT NOT NULL,
    entity_value TEXT NOT NULL,
    normalized_value TEXT NOT NULL,
    confidence REAL NOT NULL,
    start_offset INTEGER,
    end_offset INTEGER,
    UNIQUE(observation_id, entity_type, normalized_value, start_offset)
);

CREATE TABLE IF NOT EXISTS topic_evidence (
    community_id INTEGER NOT NULL REFERENCES communities(id),
    topic_key TEXT NOT NULL,
    observation_id INTEGER NOT NULL REFERENCES observations(id) ON DELETE CASCADE,
    context_key TEXT NOT NULL DEFAULT '',
    occurred_at TEXT NOT NULL,
    PRIMARY KEY(topic_key, observation_id)
);

CREATE TABLE IF NOT EXISTS raw_event_archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    installation_id INTEGER REFERENCES community_installations(id) ON DELETE SET NULL,
    observation_id INTEGER REFERENCES observations(id) ON DELETE SET NULL,
    platform TEXT NOT NULL,
    event_type TEXT NOT NULL,
    external_event_id TEXT,
    payload_sha256 TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    archive_path TEXT,
    received_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(community_id, platform, event_type, external_event_id, payload_sha256)
);

CREATE TABLE IF NOT EXISTS coordination_campaign_members (
    campaign_id INTEGER NOT NULL REFERENCES coordination_campaigns(id) ON DELETE CASCADE,
    observation_id INTEGER NOT NULL REFERENCES observations(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    similarity REAL NOT NULL,
    added_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    PRIMARY KEY(campaign_id, observation_id)
);

CREATE TABLE IF NOT EXISTS stream_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    platform TEXT NOT NULL,
    stream_key TEXT NOT NULL,
    external_stream_id TEXT,
    title TEXT,
    category TEXT,
    status TEXT NOT NULL DEFAULT 'live',
    started_at TEXT NOT NULL,
    ended_at TEXT,
    opening_observation_id INTEGER REFERENCES observations(id) ON DELETE SET NULL,
    closing_observation_id INTEGER REFERENCES observations(id) ON DELETE SET NULL,
    metrics_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(community_id, platform, stream_key, started_at)
);

CREATE TABLE IF NOT EXISTS community_announcement_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_id INTEGER NOT NULL REFERENCES community_announcements(id) ON DELETE CASCADE,
    installation_id INTEGER NOT NULL REFERENCES community_installations(id) ON DELETE CASCADE,
    attempt_number INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    provider_message_id TEXT,
    error_message TEXT,
    attempted_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    completed_at TEXT,
    UNIQUE(announcement_id, attempt_number)
);

CREATE TABLE IF NOT EXISTS message_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    attachment_index INTEGER NOT NULL,
    attachment_url TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS welcome_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_platform_account_id INTEGER NOT NULL REFERENCES platform_accounts(id) ON DELETE CASCADE,
    target_identifier TEXT NOT NULL,
    message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS twitch_channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_name TEXT NOT NULL UNIQUE,
    requested_by_platform_account_id INTEGER REFERENCES platform_accounts(id) ON DELETE SET NULL,
    request_source_message_id INTEGER REFERENCES messages(id) ON DELETE SET NULL,
    join_source TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'requested',
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS rule_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    moderation_rule_id INTEGER NOT NULL REFERENCES moderation_rules(id),
    severity TEXT NOT NULL,
    reason_code TEXT NOT NULL,
    confidence REAL,
    recommended_action TEXT,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS moderation_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    installation_id INTEGER REFERENCES community_installations(id) ON DELETE SET NULL,
    platform TEXT NOT NULL,
    message_id INTEGER REFERENCES messages(id) ON DELETE SET NULL,
    target_platform_account_id INTEGER NOT NULL REFERENCES platform_accounts(id),
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    action_type TEXT NOT NULL,
    actor_type TEXT NOT NULL,
    actor_id INTEGER,
    reason TEXT,
    duration_seconds INTEGER NOT NULL DEFAULT 600,
    status TEXT NOT NULL DEFAULT 'pending',
    error_message TEXT,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    completed_at TEXT,
    provider_status TEXT,
    provider_response_json TEXT NOT NULL DEFAULT '{}',
    assigned_operator_id INTEGER,
    escalated_at TEXT,
    provider_confirmed_at TEXT,
    provider_event_id TEXT
);

CREATE TABLE IF NOT EXISTS review_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'open',
    severity TEXT NOT NULL,
    queue_reason_code TEXT NOT NULL,
    assigned_operator_id INTEGER,
    resolution TEXT,
    resolution_note TEXT NOT NULL DEFAULT '',
    resolved_by_operator_id INTEGER,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    resolved_at TEXT
);

CREATE TABLE IF NOT EXISTS processing_job_shadow_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processing_job_id INTEGER NOT NULL REFERENCES processing_jobs(id) ON DELETE CASCADE,
    runtime TEXT NOT NULL CHECK(runtime IN ('python', 'deno')),
    status TEXT NOT NULL CHECK(status IN ('matched', 'different', 'failed')),
    result_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    UNIQUE(processing_job_id, runtime)
);

CREATE TABLE IF NOT EXISTS derived_signal_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calculation_run_id INTEGER NOT NULL REFERENCES signal_calculation_runs(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    signal_key TEXT NOT NULL,
    window_name TEXT NOT NULL,
    analyzer_version INTEGER NOT NULL,
    value_real REAL NOT NULL,
    value_json TEXT NOT NULL DEFAULT '{}',
    confidence REAL NOT NULL,
    evidence_count INTEGER NOT NULL,
    window_start TEXT,
    window_end TEXT,
    calculated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS community_derived_signal_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calculation_run_id INTEGER NOT NULL
        REFERENCES community_signal_calculation_runs(id) ON DELETE CASCADE,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    signal_key TEXT NOT NULL,
    window_name TEXT NOT NULL,
    analyzer_version INTEGER NOT NULL,
    value_real REAL NOT NULL,
    value_json TEXT NOT NULL DEFAULT '{}',
    confidence REAL NOT NULL,
    evidence_count INTEGER NOT NULL,
    window_start TEXT,
    window_end TEXT,
    calculated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS social_score_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    trigger_signal_run_id INTEGER REFERENCES signal_calculation_runs(id) ON DELETE SET NULL,
    model_version INTEGER NOT NULL,
    score INTEGER NOT NULL,
    confidence REAL NOT NULL,
    evidence_count INTEGER NOT NULL,
    band TEXT NOT NULL,
    explanation_json TEXT NOT NULL DEFAULT '{}',
    calculated_at TEXT NOT NULL,
    CHECK(confidence >= 0.0 AND confidence <= 1.0),
    CHECK(evidence_count >= 0)
);

CREATE TABLE IF NOT EXISTS dead_letter_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    observation_id INTEGER REFERENCES observations(id) ON DELETE SET NULL,
    processing_job_id INTEGER REFERENCES processing_jobs(id) ON DELETE SET NULL,
    stage TEXT NOT NULL,
    error_class TEXT NOT NULL,
    error_message TEXT NOT NULL,
    payload_json TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'open',
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    replayed_at TEXT
);

CREATE TABLE IF NOT EXISTS operations_incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    stream_session_id INTEGER REFERENCES stream_sessions(id) ON DELETE SET NULL,
    campaign_id INTEGER REFERENCES coordination_campaigns(id) ON DELETE SET NULL,
    incident_type TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'medium',
    status TEXT NOT NULL DEFAULT 'open',
    title TEXT NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    assigned_operator_id INTEGER REFERENCES operator_accounts(id) ON DELETE SET NULL,
    escalation_level INTEGER NOT NULL DEFAULT 0,
    playbook_key TEXT,
    opened_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    closed_at TEXT,
    UNIQUE(community_id, campaign_id)
);

CREATE TABLE IF NOT EXISTS post_stream_briefings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_session_id INTEGER NOT NULL UNIQUE REFERENCES stream_sessions(id) ON DELETE CASCADE,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'draft',
    title TEXT NOT NULL,
    executive_summary TEXT NOT NULL,
    metrics_json TEXT NOT NULL,
    incidents_json TEXT NOT NULL DEFAULT '[]',
    cohorts_json TEXT NOT NULL DEFAULT '{}',
    recommendations_json TEXT NOT NULL DEFAULT '[]',
    generated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    published_at TEXT
);

CREATE TABLE IF NOT EXISTS stream_cohort_snapshots (
    stream_session_id INTEGER NOT NULL REFERENCES stream_sessions(id) ON DELETE CASCADE,
    cohort_key TEXT NOT NULL,
    member_count INTEGER NOT NULL,
    message_count INTEGER NOT NULL DEFAULT 0,
    calculated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    PRIMARY KEY(stream_session_id, cohort_key)
);

CREATE TABLE IF NOT EXISTS member_appeals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    moderation_action_id INTEGER NOT NULL REFERENCES moderation_actions(id),
    appellant_platform_account_id INTEGER NOT NULL REFERENCES platform_accounts(id),
    reason TEXT NOT NULL,
    evidence_json TEXT NOT NULL DEFAULT '{}',
    severity TEXT NOT NULL DEFAULT 'medium',
    status TEXT NOT NULL DEFAULT 'open',
    assigned_operator_id INTEGER REFERENCES operator_accounts(id),
    disposition TEXT,
    resolution_note TEXT NOT NULL DEFAULT '',
    resolved_by_operator_id INTEGER REFERENCES operator_accounts(id),
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    resolved_at TEXT
);

CREATE TABLE IF NOT EXISTS derived_signal_evidence (
    signal_history_id INTEGER NOT NULL REFERENCES derived_signal_history(id) ON DELETE CASCADE,
    observation_id INTEGER REFERENCES observations(id) ON DELETE CASCADE,
    message_id INTEGER REFERENCES messages(id) ON DELETE CASCADE,
    contribution TEXT NOT NULL DEFAULT 'supporting',
    weight REAL NOT NULL DEFAULT 1.0,
    PRIMARY KEY(signal_history_id, observation_id, message_id)
);

CREATE TABLE IF NOT EXISTS intelligence_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id),
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    signal_history_id INTEGER REFERENCES derived_signal_history(id) ON DELETE SET NULL,
    observation_id INTEGER REFERENCES observations(id) ON DELETE SET NULL,
    alert_type TEXT NOT NULL,
    severity TEXT NOT NULL,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    confidence REAL NOT NULL,
    status TEXT NOT NULL DEFAULT 'open',
    disposition TEXT,
    assigned_operator_id INTEGER,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    resolved_at TEXT,
    acknowledged_at TEXT,
    suppressed_until TEXT,
    dedupe_key TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS social_score_components (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    score_run_id INTEGER NOT NULL REFERENCES social_score_runs(id) ON DELETE CASCADE,
    component_key TEXT NOT NULL,
    label TEXT NOT NULL,
    raw_value REAL NOT NULL,
    normalized_value REAL NOT NULL,
    weight REAL NOT NULL,
    contribution REAL NOT NULL,
    confidence REAL NOT NULL,
    evidence_count INTEGER NOT NULL,
    source_json TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS incident_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id INTEGER NOT NULL REFERENCES operations_incidents(id) ON DELETE CASCADE,
    operator_id INTEGER REFERENCES operator_accounts(id) ON DELETE SET NULL,
    activity_type TEXT NOT NULL,
    body TEXT NOT NULL DEFAULT '',
    payload_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS raid_playbook_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id INTEGER NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    incident_id INTEGER REFERENCES operations_incidents(id) ON DELETE SET NULL,
    playbook_key TEXT NOT NULL REFERENCES raid_playbooks(playbook_key),
    activated_by_operator_id INTEGER REFERENCES operator_accounts(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'active',
    current_step INTEGER NOT NULL DEFAULT 0,
    state_json TEXT NOT NULL DEFAULT '{}',
    activated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    completed_at TEXT
);

CREATE TABLE IF NOT EXISTS case_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id INTEGER NOT NULL REFERENCES investigation_cases(id) ON DELETE CASCADE,
    observation_id INTEGER REFERENCES observations(id) ON DELETE SET NULL,
    message_id INTEGER REFERENCES messages(id) ON DELETE SET NULL,
    signal_history_id INTEGER REFERENCES derived_signal_history(id) ON DELETE SET NULL,
    alert_id INTEGER REFERENCES intelligence_alerts(id) ON DELETE SET NULL,
    note TEXT NOT NULL DEFAULT '',
    added_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS evaluation_labels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    observation_id INTEGER REFERENCES observations(id) ON DELETE SET NULL,
    alert_id INTEGER REFERENCES intelligence_alerts(id) ON DELETE SET NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    label_key TEXT NOT NULL,
    label_value TEXT NOT NULL,
    score_key TEXT,
    score_value REAL,
    model_version INTEGER,
    operator_id INTEGER,
    source TEXT NOT NULL DEFAULT 'operator',
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS incident_alerts (
    incident_id INTEGER NOT NULL REFERENCES operations_incidents(id) ON DELETE CASCADE,
    alert_id INTEGER NOT NULL UNIQUE REFERENCES intelligence_alerts(id) ON DELETE CASCADE,
    grouped_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    PRIMARY KEY(incident_id, alert_id)
);

CREATE TABLE IF NOT EXISTS notification_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id INTEGER NOT NULL REFERENCES notification_destinations(id) ON DELETE CASCADE,
    incident_id INTEGER REFERENCES operations_incidents(id) ON DELETE CASCADE,
    alert_id INTEGER REFERENCES intelligence_alerts(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'pending',
    payload_json TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
    delivered_at TEXT
);












CREATE INDEX IF NOT EXISTS idx_twitch_install_intents_pending
    ON twitch_install_intents(expires_at) WHERE consumed_at IS NULL;



CREATE INDEX IF NOT EXISTS idx_installation_health_events_lookup
    ON installation_health_events(community_id, installation_id, checked_at DESC);













CREATE UNIQUE INDEX IF NOT EXISTS idx_operator_invitation_pending
    ON operator_invitations(community_id,target_discord_user_id)
    WHERE status='pending';





CREATE INDEX IF NOT EXISTS idx_discord_install_intents_pending
    ON discord_install_intents(expires_at) WHERE consumed_at IS NULL;



CREATE INDEX IF NOT EXISTS idx_pilot_invitations_pending
    ON pilot_invitations(community_id, expires_at) WHERE consumed_at IS NULL;















































CREATE INDEX IF NOT EXISTS idx_tenant_slo_samples_lookup
    ON tenant_slo_samples(community_id, metric_name, observed_at DESC);

CREATE INDEX IF NOT EXISTS idx_platform_accounts_user_id
    ON platform_accounts(user_id);

CREATE INDEX IF NOT EXISTS idx_messages_sent_at
    ON messages(sent_at);
CREATE INDEX IF NOT EXISTS idx_messages_platform_account
    ON messages(platform_account_id);
CREATE INDEX IF NOT EXISTS idx_message_attachments_message_id
    ON message_attachments(message_id, attachment_index);
CREATE INDEX IF NOT EXISTS idx_welcome_events_sender_target_created_at
    ON welcome_events(sender_platform_account_id, target_identifier, created_at);
CREATE INDEX IF NOT EXISTS idx_twitch_channels_status
    ON twitch_channels(status, channel_name);
CREATE INDEX IF NOT EXISTS idx_moderation_actions_created_at
    ON moderation_actions(created_at);
CREATE INDEX IF NOT EXISTS idx_reputation_events_user_id
    ON reputation_events(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_review_queue_status_created_at
    ON review_queue(status, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_log_created_at
    ON audit_log(created_at);
CREATE INDEX IF NOT EXISTS idx_server_boost_requests_lookup
    ON server_boost_requests(platform, channel_id, command_name, status, requested_at);
CREATE INDEX IF NOT EXISTS idx_server_boost_requests_expires_at
    ON server_boost_requests(expires_at);
CREATE INDEX IF NOT EXISTS idx_command_definitions_enabled
    ON command_definitions(enabled, command_name);
CREATE INDEX IF NOT EXISTS idx_simple_command_definitions_enabled
    ON simple_command_definitions(enabled, command_name);
CREATE INDEX IF NOT EXISTS idx_discord_channels_guild_name
    ON discord_channels(guild_id, channel_name);
CREATE INDEX IF NOT EXISTS idx_twitch_live_announcements_lookup
    ON twitch_live_announcements(twitch_channel_name, twitch_stream_id, discord_guild_id);
CREATE INDEX IF NOT EXISTS idx_service_reliability_buckets_lookup
    ON service_reliability_buckets(service_name, bucket_start);



CREATE INDEX IF NOT EXISTS idx_observations_occurred_at
    ON observations(occurred_at);

CREATE INDEX IF NOT EXISTS idx_observations_platform_type_time
    ON observations(platform, event_type, occurred_at);

CREATE INDEX IF NOT EXISTS idx_observations_actor_time
    ON observations(actor_platform_account_id, occurred_at);

CREATE INDEX IF NOT EXISTS idx_observations_context_time
    ON observations(context_id, occurred_at);







CREATE INDEX IF NOT EXISTS idx_processing_jobs_available
    ON processing_jobs(stage, status, available_at, priority);







CREATE INDEX IF NOT EXISTS idx_processing_jobs_observation
    ON processing_jobs(observation_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_messages_observation_id
    ON messages(observation_id)
    WHERE observation_id IS NOT NULL;





CREATE INDEX IF NOT EXISTS idx_derived_signals_user
    ON derived_signals(user_id, signal_key);

CREATE INDEX IF NOT EXISTS idx_derived_signals_key_value
    ON derived_signals(signal_key, value_real DESC);















CREATE INDEX IF NOT EXISTS idx_community_signal_windows_lookup
    ON community_derived_signal_windows(
        community_id, signal_key, window_name, value_real DESC
    );
CREATE INDEX IF NOT EXISTS idx_community_signal_history_lookup
    ON community_derived_signal_history(
        community_id, user_id, signal_key, window_name, calculated_at DESC
    );















CREATE INDEX IF NOT EXISTS idx_relationship_evidence_time
    ON relationship_evidence(relationship_id, occurred_at);









CREATE INDEX IF NOT EXISTS idx_signal_history_user_time ON derived_signal_history(user_id, calculated_at DESC);
CREATE INDEX IF NOT EXISTS idx_signal_windows_key_value ON derived_signal_windows(signal_key, window_name, value_real DESC);
CREATE INDEX IF NOT EXISTS idx_signal_evidence_observation ON derived_signal_evidence(observation_id, message_id);
CREATE INDEX IF NOT EXISTS idx_intelligence_alerts_status ON intelligence_alerts(status, severity, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cases_status ON investigation_cases(status, priority, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_relationships_source ON entity_relationships(source_user_id, strength DESC);
CREATE INDEX IF NOT EXISTS idx_reports_generated ON intelligence_reports(generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_social_score_runs_user_time ON social_score_runs(user_id, calculated_at DESC);
CREATE INDEX IF NOT EXISTS idx_social_score_components_run ON social_score_components(score_run_id, ABS(contribution) DESC);

















CREATE INDEX IF NOT EXISTS idx_content_entities_value
    ON content_entities(entity_type, normalized_value, observation_id);









CREATE INDEX IF NOT EXISTS idx_topics_velocity
    ON emerging_topics(velocity DESC, unusualness DESC);
CREATE INDEX IF NOT EXISTS idx_topics_community_velocity
    ON emerging_topics(community_id, velocity DESC, unusualness DESC);
CREATE INDEX IF NOT EXISTS idx_topic_history_time
    ON topic_history(topic_key, calculated_at DESC);









CREATE INDEX IF NOT EXISTS idx_community_graph_influence
    ON community_graph_metrics(community_id, influence_score DESC);
CREATE INDEX IF NOT EXISTS idx_community_graph_history
    ON community_graph_metric_history(community_id, user_id, calculated_at DESC);



CREATE INDEX IF NOT EXISTS idx_identity_suggestions_status
    ON identity_link_suggestions(status, confidence DESC);



CREATE INDEX IF NOT EXISTS idx_community_identity_suggestions_status
    ON community_identity_link_suggestions(community_id, status, confidence DESC);





CREATE INDEX IF NOT EXISTS idx_cohort_anomalies_score
    ON cohort_anomalies(ABS(z_score) DESC, confidence DESC);





CREATE INDEX IF NOT EXISTS idx_community_cohort_anomalies_score
    ON community_cohort_anomalies(community_id, ABS(z_score) DESC, confidence DESC);







CREATE INDEX IF NOT EXISTS idx_evaluation_runs_model_time
    ON model_evaluation_runs(model_key, calculated_at DESC);















































CREATE INDEX IF NOT EXISTS idx_shift_schedules_due
    ON moderation_shift_schedules(community_id, status, starts_at, ends_at);





















CREATE INDEX IF NOT EXISTS idx_onboarding_resources_order
    ON community_onboarding_resources(community_id, enabled, sort_order, id);

CREATE INDEX IF NOT EXISTS idx_onboarding_role_queue
    ON community_onboarding_members(role_assignment_status, community_id, joined_at);







CREATE INDEX IF NOT EXISTS idx_stream_sessions_active
    ON stream_sessions(community_id, status, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_operations_incidents_queue
    ON operations_incidents(community_id, status, severity, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_incident_activity_time
    ON incident_activity(incident_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notification_delivery_queue
    ON notification_deliveries(status, created_at);
CREATE INDEX IF NOT EXISTS idx_community_announcement_queue
    ON community_announcements(status, scheduled_at, community_id);
CREATE INDEX IF NOT EXISTS idx_community_announcement_deliveries
    ON community_announcement_deliveries(announcement_id, attempted_at DESC);
CREATE INDEX IF NOT EXISTS idx_audience_edges_community
    ON audience_edges(community_id, edge_type, weight DESC);

CREATE INDEX IF NOT EXISTS idx_campaigns_community_time
    ON coordination_campaigns(community_id, last_observed_at DESC);

CREATE INDEX IF NOT EXISTS idx_operational_metrics_time
    ON operational_metrics(metric_name, observed_at DESC);


ALTER TABLE observations ADD COLUMN IF NOT EXISTS search_vector tsvector
    GENERATED ALWAYS AS (to_tsvector('simple', COALESCE(text_raw, ''))) STORED;
CREATE INDEX IF NOT EXISTS idx_observations_search_vector
    ON observations USING GIN(search_vector);
CREATE UNIQUE INDEX IF NOT EXISTS idx_moderation_rules_community_name
    ON moderation_rules(community_id, name);
